# Generated by Django 3.0 on 2021-10-27 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Минимальная стоимость')),
                ('booking_time', models.IntegerField(verbose_name='Время брони')),
                ('price_delivery', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена доставка')),
                ('last_order', models.TextField(verbose_name='Последний заказ')),
                ('main_description', models.TextField(verbose_name='Описание ресторана')),
                ('kitchen_description', models.TextField(verbose_name='Описание кухни')),
                ('cooks_description', models.TextField(verbose_name='Описание поваров')),
                ('delivery_description', models.TextField(verbose_name='Описание доставки')),
                ('drinks_description', models.TextField(verbose_name='Описание напитков')),
                ('servic_description', models.TextField(verbose_name='Описание обслуживания')),
                ('rules_description', models.TextField(verbose_name='Описание правил')),
                ('reason_1', models.TextField(verbose_name='Причина 1')),
                ('reason_2', models.TextField(verbose_name='Причина 2')),
                ('reason_3', models.TextField(verbose_name='Причина 3')),
                ('reason_4', models.TextField(verbose_name='Причина 4')),
                ('reason_5', models.TextField(verbose_name='Причина 5')),
                ('reason_6', models.TextField(verbose_name='Причина 6')),
                ('question_1', models.TextField(verbose_name='Вопрос 1')),
                ('answer_1', models.TextField(verbose_name='Ответ 1')),
                ('question_2', models.TextField(verbose_name='Вопрос 2')),
                ('answer_2', models.TextField(verbose_name='Ответ 2')),
                ('question_3', models.TextField(verbose_name='Вопрос 3')),
                ('answer_3', models.TextField(verbose_name='Ответ 3')),
                ('question_4', models.TextField(verbose_name='Вопрос 4')),
                ('answer_4', models.TextField(verbose_name='Ответ 4')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Category', verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название блюда')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(verbose_name='Описание')),
                ('count_peoples', models.IntegerField(verbose_name='Количество людей')),
                ('structure', models.TextField(verbose_name='Cостав')),
                ('delivery', models.TextField(verbose_name='Доставка')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.Restaurant', verbose_name='Ресторан')),
            ],
        ),
    ]
