# Generated by Django 3.2.9 on 2021-11-20 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20211028_0324'),
        ('restaurants', '0002_auto_20211028_0324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='count_peoples',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='cooks_description',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='delivery_description',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='drinks_description',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='kitchen_description',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='main_description',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='price_delivery',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='rules_description',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='servic_description',
        ),
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='food',
            name='duration',
            field=models.IntegerField(null=True, verbose_name='Длительность'),
        ),
        migrations.AddField(
            model_name='food',
            name='mini_description',
            field=models.CharField(max_length=255, null=True, verbose_name='Мини описание'),
        ),
        migrations.AddField(
            model_name='food',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=9, null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='food',
            name='sale',
            field=models.DecimalField(decimal_places=0, max_digits=9, null=True, verbose_name='Скидка'),
        ),
        migrations.AddField(
            model_name='food',
            name='subcategory',
            field=models.CharField(max_length=255, null=True, verbose_name='Подкатегория'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='additionally',
            field=models.CharField(max_length=255, null=True, verbose_name='Дополнительно'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='description_1',
            field=models.TextField(null=True, verbose_name='Описание ресторана'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='description_2',
            field=models.TextField(null=True, verbose_name='Описание кухни'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='description_3',
            field=models.TextField(null=True, verbose_name='Описание поваров'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='description_4',
            field=models.TextField(null=True, verbose_name='Описание доставки'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='description_5',
            field=models.TextField(null=True, verbose_name='Описание напитков'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='description_6',
            field=models.TextField(null=True, verbose_name='Описание обслуживания'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='description_7',
            field=models.TextField(null=True, verbose_name='Описание правил'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='dishes',
            field=models.CharField(max_length=255, null=True, verbose_name='Блюда'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='kitchen_type',
            field=models.CharField(max_length=255, null=True, verbose_name='Тип кухни'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='price_departure',
            field=models.DecimalField(decimal_places=0, max_digits=9, null=True, verbose_name='Цена за доставку'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='rubric',
            field=models.CharField(max_length=255, null=True, verbose_name='Рубрика'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='service',
            field=models.BooleanField(null=True, verbose_name='Обслуживание'),
        ),
        migrations.AlterField(
            model_name='food',
            name='delivery',
            field=models.TextField(null=True, verbose_name='Доставка'),
        ),
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='food',
            name='structure',
            field=models.TextField(null=True, verbose_name='Cостав'),
        ),
    ]
