# Generated by Django 3.2.9 on 2021-11-20 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_auto_20211120_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='duration',
            field=models.IntegerField(null=True, verbose_name='Масса'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=9, verbose_name='Минимальная стоимость'),
        ),
    ]
