# Generated by Django 3.2.9 on 2021-11-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_auto_20211124_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
