# Generated by Django 3.2.9 on 2021-11-25 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_auto_20211125_1714'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RestaurantImage',
            new_name='ImageLibrary',
        ),
    ]
