# Generated by Django 3.2.9 on 2021-11-20 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decorations', '0002_auto_20211120_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='decoration',
            name='mini_description',
            field=models.CharField(max_length=255, null=True, verbose_name='Мини описание'),
        ),
        migrations.AddField(
            model_name='decoration',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=9, null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='decoration',
            name='sale',
            field=models.DecimalField(decimal_places=0, max_digits=9, null=True, verbose_name='Скидка'),
        ),
        migrations.AddField(
            model_name='decoration',
            name='subcategory',
            field=models.CharField(max_length=255, null=True, verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='decoration',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
