# Generated by Django 3.2.9 on 2021-11-24 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decorations', '0006_agencyimage_auditelement_audits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decoration',
            name='name',
        ),
        migrations.AddField(
            model_name='decoration',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
    ]
