# Generated by Django 3.2.9 on 2021-11-25 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('decorations', '0008_alter_decoration_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageLibrary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('agency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='decorations.agencydecoration', verbose_name='Агенство')),
                ('audit_element', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='decorations.auditelement', verbose_name='Элемент аудита')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('content', models.TextField(verbose_name='Текст')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decorations.agencydecoration', verbose_name='Агенство')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('content', models.TextField(verbose_name='Текст')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decorations.agencydecoration', verbose_name='Агенство')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.DeleteModel(
            name='AgencyImage',
        ),
        migrations.AddField(
            model_name='imagelibrary',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='decorations.questions', verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='imagelibrary',
            name='reviews',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='decorations.reviews', verbose_name='Отзывы'),
        ),
    ]
