# Generated by Django 3.2.9 on 2021-11-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decorations', '0010_auto_20211126_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencydecoration',
            name='price_delivery',
            field=models.DecimalField(decimal_places=0, max_digits=9, verbose_name='Доставка'),
        ),
        migrations.AlterField(
            model_name='agencydecoration',
            name='price_departure',
            field=models.DecimalField(decimal_places=0, max_digits=9, verbose_name='Цена за выезд'),
        ),
    ]
