# Generated by Django 3.0 on 2021-11-26 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decorations', '0011_auto_20211126_2042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='decoration',
            old_name='mini_description',
            new_name='mini_descr',
        ),
    ]
