# Generated by Django 3.0 on 2021-11-26 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decorations', '0012_auto_20211127_0016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='decoration',
            old_name='mini_descr',
            new_name='mini_desc',
        ),
    ]
