# Generated by Django 3.2.9 on 2021-12-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decorations', '0013_auto_20211127_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencydecoration',
            name='additionally',
            field=models.CharField(choices=[('Нет дополнений', 'Нет дополнений'), ('Живые цветы', 'Живые цветы'), ('Фотозона', 'Фотозона'), ('Аксессуар для гостей', 'Аксессуар для гостей'), ('Персонализация', 'Персонализация'), ('Пригласительные', 'Пригласительные')], default='Нет дополнений', max_length=255, null=True, verbose_name='Дополнительно'),
        ),
        migrations.AlterField(
            model_name='agencydecoration',
            name='design_elements',
            field=models.CharField(choices=[('Воздушные шары', 'Воздушные шары'), ('Шары-цифры', 'Шары-цифры'), ('Арка из шаров', 'Арка из шаров'), ('Букеты из шаров', 'Букеты из шаров'), ('Фигруы из шаров', 'Фигруы из шаров'), ('Шар-сюрприз', 'Шар-сюрприз'), ('Ростовые куклы', 'Ростовые куклы'), ('Баннеры на стене', 'Баннеры на стене'), ('Фон из пайеток', 'Фон из пайеток'), ('Гирлянды', 'Гирлянды'), ('Бумажные украшения', 'Бумажные украшения')], default='Воздушные шары', max_length=255, verbose_name='Элементы оформления'),
        ),
        migrations.AlterField(
            model_name='agencydecoration',
            name='rubric',
            field=models.CharField(choices=[('Комплексное оформление', 'Комплексное оформление'), ('Тематические наборы', 'Тематические наборы'), ('Оформление стола', 'Оформление стола'), ('Акции %', 'Акции %')], default='Комплексное оформление', max_length=255, verbose_name='Разновидность'),
        ),
    ]
