# Generated by Django 3.2.9 on 2021-12-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidays',
            name='structure',
            field=models.CharField(choices=[('Аренда помещения', 'Аренда помещения'), ('Угощение', 'Угощение'), ('Развлечения', 'Развлечения'), ('Праздничное оформление', 'Праздничное оформление'), ('Фото и видеосъёмка', 'Фото и видеосъёмка')], default='Аренда помещения', max_length=255, verbose_name='Что включено'),
        ),
        migrations.AlterField(
            model_name='holidays',
            name='guests_age',
            field=models.CharField(choices=[('От 1 года до 3 лет', 'От 1 года до 3 лет'), ('От 3 до 7 лет', 'От 3 до 7 лет'), ('От 8 до 12 лет', 'От 8 до 12 лет'), ('12+ лет', '12+ лет')], default='От 1 года до 3 лет', max_length=255, verbose_name='Возраст гостей'),
        ),
        migrations.AlterField(
            model_name='holidays',
            name='guests_gender',
            field=models.CharField(choices=[('Для мальчика', 'Для мальчика'), ('Для девочки', 'Для девочки'), ('Для всех сразу', 'Для всех сразу')], default='Для всех сразу', max_length=255, verbose_name='Пол гостей'),
        ),
    ]
