# Generated by Django 3.2.9 on 2021-12-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0002_auto_20211213_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidays',
            name='district',
            field=models.CharField(choices=[('Адмиралтейский', 'Адмиралтейский'), ('Василеостровский', 'Василеостровский'), ('Выборгский', 'Выборгский'), ('Калининский', 'Калининский'), ('Кировский', 'Кировский'), ('Коллинский', 'Коллинский'), ('Красногвардейский', 'Красногвардейский'), ('Красносельский', 'Красносельский'), ('Кронштадский', 'Кронштадский')], default='Адмиралтейский', max_length=255, null=True, verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='holidays',
            name='structure',
            field=models.CharField(choices=[('Аренда помещения', 'Аренда помещения'), ('Угощения', 'Угощения'), ('Развлечения', 'Развлечения'), ('Праздничное оформление', 'Праздничное оформление'), ('Фото и видеосъёмка', 'Фото и видеосъёмка')], default='Аренда помещения', max_length=255, verbose_name='Что включено'),
        ),
    ]
