# Generated by Django 3.2.9 on 2021-12-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyphotos',
            name='result',
            field=models.CharField(choices=[('Фотокнига', 'Фотокнига'), ('Печать на холсте', 'Печать на холсте'), ('DVD-диск', 'DVD-диск'), ('Печать фото', 'Печать фото'), ('Клип', 'Клип'), ('Фильм', 'Фильм')], default='Фотокнига', max_length=255, verbose_name='Рузультат'),
        ),
        migrations.AlterField(
            model_name='agencyphotos',
            name='rubric',
            field=models.CharField(choices=[('Комплексная фото- и видеосъёмка', 'Комплексная фото- и видеосъёмка'), ('Только фото', 'Только фото'), ('Только видео', 'Только видео'), ('Акции %', 'Акции %')], default='Только фото', max_length=255, verbose_name='Разновидность'),
        ),
        migrations.AlterField(
            model_name='agencyphotos',
            name='types_conditions',
            field=models.CharField(choices=[('Фотосессия', 'Фотосессия'), ('Репортажная съёмка', 'Репортажная съёмка'), ('Портретная съёмка', 'Портретная съёмка'), ('Съёмка в студии', 'Съёмка в студии'), ('Съёмка дома или на природе', 'Съёмка дома или на природе'), ('Профессиональная ретушь', 'Профессиональная ретушь'), ('Съёмка мероприятия', 'Съёмка мероприятия'), ('Помощь в подборе одежды', 'Помощь в подборе одежды'), ('Аренда аксессуаров', 'Аренда аксессуаров'), ('Цветовая коррекция', 'Цветовая коррекция')], default='Фотосессия', max_length=255, verbose_name='Виды и условия'),
        ),
    ]
