# Generated by Django 3.2.9 on 2021-12-14 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20211213_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyphotos',
            name='last_order',
            field=models.CharField(max_length=255, verbose_name='Последний заказ'),
        ),
        migrations.AlterField(
            model_name='agencyphotos',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Минимальная стоимость часа'),
        ),
    ]
