# Generated by Django 3.2.9 on 2021-12-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20211214_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyphotos',
            name='description_1',
            field=models.TextField(null=True, verbose_name='Описание агенства'),
        ),
        migrations.AlterField(
            model_name='agencyphotos',
            name='description_2',
            field=models.TextField(null=True, verbose_name='Описание студии'),
        ),
        migrations.AlterField(
            model_name='agencyphotos',
            name='description_3',
            field=models.TextField(null=True, verbose_name='Описание реквизита'),
        ),
        migrations.AlterField(
            model_name='agencyphotos',
            name='description_4',
            field=models.TextField(null=True, verbose_name='Описание позирование'),
        ),
        migrations.AlterField(
            model_name='agencyphotos',
            name='description_5',
            field=models.TextField(null=True, verbose_name='Описание нарядов'),
        ),
        migrations.AlterField(
            model_name='agencyphotos',
            name='description_6',
            field=models.TextField(null=True, verbose_name='Описание времени'),
        ),
    ]
