# Generated by Django 3.0 on 2021-12-08 22:07

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('mini_desc', models.TextField(max_length=255, verbose_name='')),
                ('content', mdeditor.fields.MDTextField()),
            ],
        ),
    ]
