# Generated by Django 3.0 on 2021-12-08 22:39

from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(verbose_name='Прошел модерацию')),
                ('name', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('content', models.TextField(verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.CreateModel(
            name='Rubrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Имя категории')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Рубрика статьи',
                'verbose_name_plural': 'Рубрики статей',
            },
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Cтатья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AddField(
            model_name='blog',
            name='date',
            field=models.DateField(null=True, verbose_name='Дата статьи'),
        ),
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Изобажение'),
        ),
        migrations.AddField(
            model_name='blog',
            name='status',
            field=models.BooleanField(null=True, verbose_name='Не публиковать'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=mdeditor.fields.MDTextField(null=True, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='mini_desc',
            field=models.TextField(max_length=255, verbose_name='Мини описание'),
        ),
        migrations.AddField(
            model_name='blog',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Comments', verbose_name='Комментарии'),
        ),
        migrations.AddField(
            model_name='blog',
            name='rubric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Rubrics', verbose_name='Рубрика'),
        ),
    ]
