# Generated by Django 3.0 on 2021-12-08 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211209_0139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Cтатью', 'verbose_name_plural': 'Статьи'},
        ),
    ]
