# Generated by Django 3.2.9 on 2021-12-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comments_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.BooleanField(verbose_name='Не публиковать'),
        ),
    ]
