# Generated by Django 3.0 on 2021-10-28 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animators', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animator',
            options={'verbose_name': 'Аниматор', 'verbose_name_plural': 'Аниматоры'},
        ),
    ]
