# Generated by Django 3.2.9 on 2021-11-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animators', '0002_auto_20211028_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='additionally',
            field=models.CharField(max_length=255, null=True, verbose_name='Дополнительно'),
        ),
        migrations.AddField(
            model_name='agency',
            name='guests_age',
            field=models.CharField(max_length=255, null=True, verbose_name='Возраст гостей'),
        ),
        migrations.AddField(
            model_name='agency',
            name='joint_entertainment',
            field=models.CharField(max_length=255, null=True, verbose_name='Совместные развлечения'),
        ),
        migrations.AddField(
            model_name='agency',
            name='rubric',
            field=models.CharField(max_length=255, null=True, verbose_name='Рубрика'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='duration',
            field=models.IntegerField(null=True, verbose_name='Минимальная длительность'),
        ),
    ]
