# Generated by Django 3.2.9 on 2021-11-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animators', '0003_auto_20211119_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='requisite_description',
            field=models.TextField(verbose_name='Описание реквизита'),
        ),
    ]
