# Generated by Django 3.2.9 on 2021-11-19 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animators', '0004_alter_agency_requisite_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animator',
            name='agency',
        ),
        migrations.AddField(
            model_name='animator',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='animators.agency', verbose_name='Название'),
        ),
    ]
