# Generated by Django 3.2.9 on 2021-11-19 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animators', '0007_auto_20211119_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animator',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animators.agency', verbose_name='Агенство'),
        ),
    ]
