# Generated by Django 3.2.9 on 2021-11-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animators', '0008_alter_animator_agency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='agency_description',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='music_description',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='prasent_description',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='program_description',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='requisite_description',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='rules_description',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='time_description',
        ),
        migrations.AddField(
            model_name='agency',
            name='description_1',
            field=models.TextField(null=True, verbose_name='Описание агенства'),
        ),
        migrations.AddField(
            model_name='agency',
            name='description_2',
            field=models.TextField(null=True, verbose_name='Описание программы'),
        ),
        migrations.AddField(
            model_name='agency',
            name='description_3',
            field=models.TextField(null=True, verbose_name='Описание реквизита'),
        ),
        migrations.AddField(
            model_name='agency',
            name='description_4',
            field=models.TextField(null=True, verbose_name='Описание подарков'),
        ),
        migrations.AddField(
            model_name='agency',
            name='description_5',
            field=models.TextField(null=True, verbose_name='Описание музыки'),
        ),
        migrations.AddField(
            model_name='agency',
            name='description_6',
            field=models.TextField(null=True, verbose_name='Описание времени'),
        ),
        migrations.AddField(
            model_name='agency',
            name='description_7',
            field=models.TextField(null=True, verbose_name='Описание правил'),
        ),
        migrations.AlterField(
            model_name='animator',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
