# Generated by Django 3.2.9 on 2021-11-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animators', '0011_auto_20211119_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='animator',
            name='mini_description',
            field=models.CharField(max_length=255, null=True, verbose_name='Мини описание'),
        ),
    ]
