# Generated by Django 3.2.9 on 2021-11-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animators', '0012_animator_mini_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='animator',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=9, null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='animator',
            name='sale',
            field=models.DecimalField(decimal_places=0, max_digits=9, null=True, verbose_name='Скидка'),
        ),
    ]
