# Generated by Django 3.0 on 2021-11-23 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animators', '0015_agencyimage_auditelement_audits'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audits',
            old_name='agnecy',
            new_name='agency',
        ),
    ]
