# Generated by Django 3.2.9 on 2021-11-24 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animators', '0016_auto_20211123_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animator',
            name='name',
        ),
        migrations.AddField(
            model_name='animator',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
    ]
