# Generated by Django 3.2.9 on 2021-12-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animators', '0021_auto_20211127_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='additionally',
            field=models.CharField(choices=[('Нет дополнений', 'Нет дополнений'), ('Аквагрим', 'Аквагрим'), ('Караоке', 'Караоке'), ('Шоколадный фонтан', 'Шоколадный фонтан'), ('Ручные животные', 'Ручные животные')], default='Нет дополнений', max_length=255, null=True, verbose_name='Дополнительно'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='guests_age',
            field=models.CharField(choices=[('От 1 года до 3 лет', 'От 1 года до 3 лет'), ('От 3 до 7 лет', 'От 3 до 7 лет'), ('От 8 до 12 лет', 'От 8 до 12 лет'), ('12+ лет', '12+ лет')], default='От 1 года до 3 лет', max_length=255, verbose_name='Возраст гостей'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='joint_entertainment',
            field=models.CharField(choices=[('Шоу мыльных пузырей', 'Шоу мыльных пузырей'), ('Ютуб-вечеринка', 'Ютуб-вечеринка'), ('Шоу мороженого', 'Шоу мороженого'), ('Фокусник', 'Фокусник'), ('Конфетти-шоу', 'Конфетти-шоу'), ('Шоу трансформеров', 'Шоу трансформеров'), ('Научное шоу', 'Научное шоу'), ('Бумажное шоу', 'Бумажное шоу'), ('Квест', 'Квест'), ('Дино-шоу', 'Дино-шоу'), ('Шерстяное шоу', 'Шерстяное шоу'), ('Спектакль', 'Спектакль')], default='Шоу мыльных пузырей', max_length=255, verbose_name='Совместные развлечения'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='rubric',
            field=models.CharField(choices=[('Детское шоу', 'Детское шоу'), ('Аниматор', 'Аниматор'), ('Выезд на место', 'Выезд на место'), ('Акции %', 'Акции %')], default='Аниматор', max_length=255, verbose_name='Разновидность'),
        ),
    ]
