# Generated by Django 3.2.8 on 2021-11-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premises', '0002_auto_20211028_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='premises',
            name='friday',
            field=models.CharField(max_length=255, null=True, verbose_name='Пятница'),
        ),
        migrations.AddField(
            model_name='premises',
            name='monday',
            field=models.CharField(max_length=255, null=True, verbose_name='Понедельник'),
        ),
        migrations.AddField(
            model_name='premises',
            name='saturday',
            field=models.CharField(max_length=255, null=True, verbose_name='Суббота'),
        ),
        migrations.AddField(
            model_name='premises',
            name='sunday',
            field=models.CharField(max_length=255, null=True, verbose_name='Воскресенье'),
        ),
        migrations.AddField(
            model_name='premises',
            name='thursday',
            field=models.CharField(max_length=255, null=True, verbose_name='Четверг'),
        ),
        migrations.AddField(
            model_name='premises',
            name='tuesday',
            field=models.CharField(max_length=255, null=True, verbose_name='Вторник'),
        ),
        migrations.AddField(
            model_name='premises',
            name='wednesday',
            field=models.CharField(max_length=255, null=True, verbose_name='Среда'),
        ),
    ]
