# Generated by Django 3.2.8 on 2021-11-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premises', '0003_auto_20211114_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='premises',
            name='additionally',
            field=models.CharField(max_length=255, null=True, verbose_name='Дополнительно'),
        ),
        migrations.AddField(
            model_name='premises',
            name='conditions',
            field=models.CharField(max_length=255, null=True, verbose_name='Условия'),
        ),
        migrations.AddField(
            model_name='premises',
            name='district',
            field=models.CharField(max_length=255, null=True, verbose_name='Район'),
        ),
        migrations.AddField(
            model_name='premises',
            name='zoning',
            field=models.CharField(max_length=255, null=True, verbose_name='Зонирование'),
        ),
    ]
