# Generated by Django 3.2.8 on 2021-11-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premises', '0004_auto_20211114_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premises',
            name='count_peoples',
            field=models.CharField(max_length=255, verbose_name='Вместимость'),
        ),
    ]
