# Generated by Django 3.2.8 on 2021-11-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premises', '0005_alter_premises_count_peoples'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premises',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=9, verbose_name='Цена за час'),
        ),
        migrations.AlterField(
            model_name='premises',
            name='sale',
            field=models.DecimalField(decimal_places=0, max_digits=9, verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='premises',
            name='square',
            field=models.DecimalField(decimal_places=0, max_digits=9, verbose_name='Площадь'),
        ),
    ]
