# Generated by Django 3.2.9 on 2021-11-18 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premises', '0006_auto_20211116_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='premises',
            name='answer_1',
            field=models.TextField(null=True, verbose_name='Ответ 1'),
        ),
        migrations.AddField(
            model_name='premises',
            name='answer_2',
            field=models.TextField(null=True, verbose_name='Ответ 2'),
        ),
        migrations.AddField(
            model_name='premises',
            name='answer_3',
            field=models.TextField(null=True, verbose_name='Ответ 3'),
        ),
        migrations.AddField(
            model_name='premises',
            name='answer_4',
            field=models.TextField(null=True, verbose_name='Ответ 4'),
        ),
        migrations.AddField(
            model_name='premises',
            name='description_1',
            field=models.TextField(null=True, verbose_name='Описание помещения'),
        ),
        migrations.AddField(
            model_name='premises',
            name='description_2',
            field=models.TextField(null=True, verbose_name='Описание звукового оборудования'),
        ),
        migrations.AddField(
            model_name='premises',
            name='description_3',
            field=models.TextField(null=True, verbose_name='Описание светового и шоу оборудования'),
        ),
        migrations.AddField(
            model_name='premises',
            name='description_4',
            field=models.TextField(null=True, verbose_name='Описание технического оборудования'),
        ),
        migrations.AddField(
            model_name='premises',
            name='description_5',
            field=models.TextField(null=True, verbose_name='Описание мебели'),
        ),
        migrations.AddField(
            model_name='premises',
            name='description_6',
            field=models.TextField(null=True, verbose_name='Описание правил'),
        ),
        migrations.AddField(
            model_name='premises',
            name='description_7',
            field=models.TextField(null=True, verbose_name='Описание кихни и посуды'),
        ),
        migrations.AddField(
            model_name='premises',
            name='question_1',
            field=models.TextField(null=True, verbose_name='Вопрос 1'),
        ),
        migrations.AddField(
            model_name='premises',
            name='question_2',
            field=models.TextField(null=True, verbose_name='Вопрос 2'),
        ),
        migrations.AddField(
            model_name='premises',
            name='question_3',
            field=models.TextField(null=True, verbose_name='Вопрос 3'),
        ),
        migrations.AddField(
            model_name='premises',
            name='question_4',
            field=models.TextField(null=True, verbose_name='Вопрос 4'),
        ),
        migrations.AddField(
            model_name='premises',
            name='reason_1',
            field=models.TextField(null=True, verbose_name='Причина 1'),
        ),
        migrations.AddField(
            model_name='premises',
            name='reason_2',
            field=models.TextField(null=True, verbose_name='Причина 2'),
        ),
        migrations.AddField(
            model_name='premises',
            name='reason_3',
            field=models.TextField(null=True, verbose_name='Причина 3'),
        ),
        migrations.AddField(
            model_name='premises',
            name='reason_4',
            field=models.TextField(null=True, verbose_name='Причина 4'),
        ),
        migrations.AddField(
            model_name='premises',
            name='reason_5',
            field=models.TextField(null=True, verbose_name='Причина 5'),
        ),
        migrations.AddField(
            model_name='premises',
            name='reason_6',
            field=models.TextField(null=True, verbose_name='Причина 6'),
        ),
        migrations.AlterField(
            model_name='premises',
            name='sale',
            field=models.DecimalField(decimal_places=0, max_digits=9, verbose_name='Цена по скидке'),
        ),
    ]
