# Generated by Django 3.2.9 on 2021-11-18 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premises', '0007_auto_20211118_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premises',
            name='answer_4',
            field=models.TextField(verbose_name='Ответ 4'),
        ),
    ]
