# Generated by Django 3.2.9 on 2021-11-18 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premises', '0008_alter_premises_answer_4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premises',
            name='answer_4',
            field=models.TextField(null=True, verbose_name='Ответ 4'),
        ),
    ]
