# Generated by Django 3.2.9 on 2021-11-18 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premises', '0009_alter_premises_answer_4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premises',
            name='video',
            field=models.FileField(null=True, upload_to='', verbose_name='Видео'),
        ),
    ]
