# Generated by Django 3.2.9 on 2021-11-18 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premises', '0010_alter_premises_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premises',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Видео'),
        ),
    ]
