# Generated by Django 3.2.9 on 2021-11-21 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('premises', '0013_alter_premises_mini_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premisesimage',
            name='premises',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='premises.premises', verbose_name='Помещение'),
        ),
        migrations.CreateModel(
            name='Audits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premises', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='premises.premises', verbose_name='Помещение')),
            ],
            options={
                'verbose_name': 'Аудит',
                'verbose_name_plural': 'Аудиты',
            },
        ),
        migrations.CreateModel(
            name='AuditElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('content', models.TextField(null=True, verbose_name='Текст')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='premises.audits', verbose_name='Аудит')),
            ],
            options={
                'verbose_name': 'Элемент аудита',
                'verbose_name_plural': 'Элементы аудитов',
            },
        ),
    ]
