# Generated by Django 3.2.9 on 2021-11-21 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('premises', '0014_auto_20211121_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditelement',
            name='audit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='premises.audits', verbose_name='Аудит'),
        ),
        migrations.AlterField(
            model_name='auditelement',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
    ]
