# Generated by Django 3.2.9 on 2021-11-21 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('premises', '0015_auto_20211121_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='premisesimage',
            name='audit_element',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='premises.auditelement', verbose_name='Элемент аудита'),
        ),
    ]
