# Generated by Django 3.2.9 on 2021-11-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premises', '0016_premisesimage_audit_element'),
    ]

    operations = [
        migrations.AddField(
            model_name='audits',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
    ]
