# Generated by Django 3.2.9 on 2021-11-21 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('premises', '0017_audits_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audits',
            old_name='premises',
            new_name='premise',
        ),
    ]
