# Generated by Django 3.2.9 on 2021-11-21 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('premises', '0018_rename_premises_audits_premise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audits',
            name='premise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='premises.premises', verbose_name='Помещение'),
        ),
    ]
