# Generated by Django 3.2.9 on 2021-11-25 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('premises', '0021_auto_20211125_0102'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PremisesImage',
            new_name='ImageLibrary',
        ),
    ]
