# Generated by Django 3.2.9 on 2021-11-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premises', '0022_rename_premisesimage_imagelibrary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premises',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=9, verbose_name='Цена без скидки'),
        ),
        migrations.AlterField(
            model_name='premises',
            name='sale',
            field=models.DecimalField(decimal_places=0, max_digits=9, verbose_name='Цена со скидкой'),
        ),
    ]
