# Generated by Django 3.2.9 on 2021-11-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premises', '0023_auto_20211126_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='premises',
            name='map_link',
            field=models.CharField(max_length=255, null=True, verbose_name='Ссылка на картку'),
        ),
    ]
