# Generated by Django 3.2.9 on 2021-12-15 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premises', '0026_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=255, verbose_name='Название')),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.RemoveField(
            model_name='premises',
            name='count_peoples',
        ),
        migrations.AddField(
            model_name='premises',
            name='count_peoples',
            field=models.ManyToManyField(to='premises.Choices'),
        ),
    ]
