# Generated by Django 3.2.9 on 2021-12-15 04:50

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('premises', '0028_auto_20211215_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premises',
            name='additionally',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Нет дополнений', 'Нет дополнений'), ('Оборудованная кузня', 'Оборудованная кузня'), ('Посуда', 'Посуда'), ('Музоборудование', 'Музоборудование'), ('Кондиционер', 'Кондиционер'), ('Стол для малышей', 'Стол для малышей'), ('Парковка', 'Парковка')], default='Нет дополнений', max_length=255, null=True, verbose_name='Дополнительно'),
        ),
        migrations.AlterField(
            model_name='premises',
            name='conditions',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Нет условий', 'Нет условий'), ('Закрывается под нас', 'Закрывается под нас'), ('Отдельный вход', 'Отдельный вход'), ('Можно со своей едой', 'Можно со своей едой'), ('Можно со своим фотогрофом/аниматором', 'Можно со своим фотогрофом/аниматором'), ('Можно украсить самим', 'Можно украсить самим'), ('Уборка после включена', 'Уборка после включена')], default='Нет условий', max_length=255, null=True, verbose_name='Условия'),
        ),
        migrations.AlterField(
            model_name='premises',
            name='zoning',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Нет зонирования', 'Нет зонирования'), ('Место для игр', 'Место для игр'), ('Место для переодевания', 'Место для переодевания'), ('Место для красивых фото', 'Место для красивых фото'), ('Тихий уголокдля взрослых', 'Тихий уголокдля взрослых')], default='Нет зонирования', max_length=255, null=True, verbose_name='Зонирование'),
        ),
    ]
